# Generated by Django 5.0.6 on 2024-07-10 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_alter_postassignment_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentHelper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('age', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('phone_no', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('education', models.CharField(blank=True, max_length=100)),
                ('profile_picture', models.ImageField(blank=True, upload_to='')),
                ('experience_years', models.PositiveIntegerField()),
                ('total_assignment_done', models.PositiveIntegerField()),
                ('average_rating', models.PositiveIntegerField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('mastery_subjects', models.ManyToManyField(to='client.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='helper.assignmenthelper')),
            ],
        ),
    ]
