# Generated by Django 5.2.8 on 2025-11-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmenthelper",
            name="pp",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="helper/images",
                verbose_name="Profile Picture",
            ),
        ),
    ]
