# Generated by Django 5.2.8 on 2025-11-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commonuser",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="authentication/images"
            ),
        ),
    ]
