# Generated by Django 5.2.7 on 2025-10-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_baseuser_commonuser_delete_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="commonuser",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Is Staff"),
        ),
    ]
