# Generated by Django 5.2.8 on 2025-11-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_commonuser_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commonuser",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="First "),
        ),
    ]
