# Generated by Django 5.2.8 on 2026-01-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_commonuser_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="commonuser",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                unique=True,
                verbose_name="Username",
            ),
        ),
        migrations.AlterField(
            model_name="commonuser",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="First Name"),
        ),
    ]
