# Generated by Django 5.2.8 on 2026-01-31 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstagramAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "instagram_business_account_id",
                    models.CharField(max_length=255, unique=True),
                ),
                ("instagram_username", models.CharField(max_length=255)),
                ("access_token", models.TextField()),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("facebook_page_id", models.CharField(max_length=255)),
                ("facebook_page_name", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instagram_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Instagram Account",
                "verbose_name_plural": "Instagram Accounts",
                "db_table": "instagram_accounts",
            },
        ),
        migrations.CreateModel(
            name="InstagramConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("conversation_id", models.CharField(max_length=255, unique=True)),
                ("participant_instagram_id", models.CharField(max_length=255)),
                ("participant_username", models.CharField(blank=True, max_length=255)),
                ("participant_name", models.CharField(blank=True, max_length=255)),
                ("participant_profile_pic", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_message_time", models.DateTimeField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "instagram_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="insta_connect.instagramaccount",
                    ),
                ),
            ],
            options={
                "db_table": "instagram_conversations",
                "ordering": ["-last_message_time"],
            },
        ),
        migrations.CreateModel(
            name="InstagramMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=255, unique=True)),
                ("is_from_business", models.BooleanField(default=False)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("story_mention", "Story Mention"),
                            ("story_reply", "Story Reply"),
                            ("reel_share", "Reel Share"),
                            ("like", "Like"),
                            ("unsupported", "Unsupported"),
                        ],
                        default="text",
                        max_length=50,
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("media_url", models.URLField(blank=True)),
                ("timestamp", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="insta_connect.instagramconversation",
                    ),
                ),
            ],
            options={
                "db_table": "instagram_messages",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("raw_data", models.JSONField()),
                ("processed", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "instagram_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_events",
                        to="insta_connect.instagramaccount",
                    ),
                ),
            ],
            options={
                "db_table": "webhook_events",
                "ordering": ["-received_at"],
            },
        ),
        migrations.AddIndex(
            model_name="instagramconversation",
            index=models.Index(
                fields=["instagram_account", "-last_message_time"],
                name="instagram_c_instagr_1a22dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="instagramconversation",
            index=models.Index(
                fields=["conversation_id"], name="instagram_c_convers_de1025_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instagrammessage",
            index=models.Index(
                fields=["conversation", "timestamp"],
                name="instagram_m_convers_fdb7c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="instagrammessage",
            index=models.Index(
                fields=["message_id"], name="instagram_m_message_1af6ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["processed", "received_at"],
                name="webhook_eve_process_b7e4c3_idx",
            ),
        ),
    ]
