# Generated by Django 5.2.8 on 2026-01-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InstagramSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "app_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Instagram App ID"
                    ),
                ),
                (
                    "app_secret",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Instagram App Secret"
                    ),
                ),
                (
                    "api_version",
                    models.CharField(
                        default="v20.0", max_length=10, verbose_name="API Version"
                    ),
                ),
                (
                    "webhook_verify_token",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Webhook Verify Token"
                    ),
                ),
            ],
            options={
                "verbose_name": "Instagram Settings",
                "verbose_name_plural": "Instagram Settings",
                "db_table": "instagram_settings",
            },
        ),
    ]
