# Generated by Django 6.0.5 on 2026-05-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writerprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='writers/cvs/', verbose_name='CV'),
        ),
    ]
