# Generated by Django 6.0.5 on 2026-05-14 17:58

import django.db.models.deletion
from django.db import migrations, models


SERVICE_CATEGORIES = [
    ("Writing & Research", 1),
    ("Business & Data", 2),
    ("Technology", 3),
    ("Specialist Subjects", 4),
    ("Presentations", 5),
]

SERVICE_CATEGORY_MAP = {
    "Editing & Proofreading": "Writing & Research",
    "Essay Writing": "Writing & Research",
    "Report Writing": "Writing & Research",
    "Research Papers": "Writing & Research",
    "Thesis & Dissertation": "Writing & Research",
    "Business & Management": "Business & Data",
    "Case Study Analysis": "Business & Data",
    "Data Analysis & Excel": "Business & Data",
    "Finance & Accounting": "Business & Data",
    "IT & Computer Science": "Technology",
    "Website Development": "Technology",
    "Healthcare & Nursing": "Specialist Subjects",
    "Presentation Slides": "Presentations",
}


def seed_service_categories(apps, schema_editor):
    Service = apps.get_model("writers", "Service")
    ServiceCategory = apps.get_model("writers", "ServiceCategory")

    categories = {}
    for name, sort_order in SERVICE_CATEGORIES:
        category, _ = ServiceCategory.objects.get_or_create(
            name=name,
            defaults={"sort_order": sort_order},
        )
        categories[name] = category

    for service_name, category_name in SERVICE_CATEGORY_MAP.items():
        Service.objects.filter(name=service_name).update(category=categories[category_name])


def unassign_service_categories(apps, schema_editor):
    Service = apps.get_model("writers", "Service")
    Service.objects.update(category=None)


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0003_service_writerprofile_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
            ],
            options={
                'verbose_name_plural': 'Service categories',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('category__sort_order', 'category__name', 'name')},
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='writers.servicecategory'),
        ),
        migrations.RunPython(seed_service_categories, unassign_service_categories),
    ]
