# Generated by Django 6.0.5 on 2026-05-15 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0005_seed_presentations_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='writerprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='writerprofile',
            name='experience_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)], verbose_name='Years of Experience'),
        ),
        migrations.AddField(
            model_name='writerprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=160, verbose_name='Headline'),
        ),
        migrations.AddField(
            model_name='writerprofile',
            name='languages',
            field=models.CharField(blank=True, max_length=255, verbose_name='Languages'),
        ),
        migrations.AddField(
            model_name='writerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=120, verbose_name='Location'),
        ),
    ]
