# Generated by Django 6.0.5 on 2026-05-15 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0006_writerprofile_bio_writerprofile_experience_years_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterWorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='writers/work-images/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('writer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_images', to='writers.writerprofile')),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
            },
        ),
    ]
