# Generated by Django 6.0.5 on 2026-05-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0007_writerworkimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writerprofile',
            name='experience_years',
        ),
    ]
