# Generated by Django 6.0.5 on 2026-05-15 10:19

from django.db import migrations


def copy_writer_profile_pictures(apps, schema_editor):
    WriterProfile = apps.get_model("writers", "WriterProfile")

    for profile in WriterProfile.objects.exclude(profile_picture="").select_related("user"):
        profile.user.profile_picture = profile.profile_picture
        profile.user.save(update_fields=["profile_picture"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_picture'),
        ('writers', '0008_remove_writerprofile_experience_years'),
    ]

    operations = [
        migrations.RunPython(copy_writer_profile_pictures, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='writerprofile',
            name='profile_picture',
        ),
    ]
