# Generated by Django 6.0.5 on 2026-05-15 10:26

from django.db import migrations


def copy_writer_locations(apps, schema_editor):
    WriterProfile = apps.get_model("writers", "WriterProfile")

    for profile in WriterProfile.objects.exclude(location="").select_related("user"):
        if not profile.user.location:
            profile.user.location = profile.location
            profile.user.save(update_fields=["location"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_location'),
        ('writers', '0009_remove_writerprofile_profile_picture'),
    ]

    operations = [
        migrations.RunPython(copy_writer_locations, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='writerprofile',
            name='location',
        ),
    ]
