# Generated by Django 6.0.5 on 2026-05-15 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0010_remove_writerprofile_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writerprofile',
            name='rating',
        ),
        migrations.AddField(
            model_name='writerprofile',
            name='starting_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Starting Price'),
        ),
        migrations.CreateModel(
            name='WriterFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('writer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='writers.writerprofile')),
            ],
            options={
                'verbose_name': 'Writer FAQ',
                'verbose_name_plural': 'Writer FAQs',
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='WriterReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')])),
                ('comment', models.TextField(blank=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writer_reviews', to=settings.AUTH_USER_MODEL)),
                ('writer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='writers.writerprofile')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('writer_profile', 'reviewer'), name='unique_review_per_reviewer')],
            },
        ),
    ]
