# Generated by Django 6.0.5 on 2026-05-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0011_remove_writerprofile_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writerprofile',
            name='delivery_days_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writerprofile',
            name='delivery_days_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
