# Generated by Django 6.0.5 on 2026-05-15 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0012_writerprofile_delivery_days_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterPerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=120)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('writer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perks', to='writers.writerprofile')),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
            },
        ),
    ]
