# Generated by Django 5.0.6 on 2024-07-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postassignment',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
