# Generated by Django 5.0.6 on 2025-03-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_postassignment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postassignment',
            name='upload_file',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
